board/urls.py
from django.urls import path, include
from . import views
urlpatterns = [
    # 질문 목록
    path('', views.index,name='question'),  # http://127.0.0.1:8000/board/  
    
    # 질문 상세
    path('<int:id>', views.detail ,name='detail'),  # http://127.0.0.1:8000/board/question/

    # 답변 등록
    path('answer/create/<int:id>',views.answer_create, name='answer_create'),
    # 답변 삭제
    path('answer/delete/<int:id>',views.answer_delete, name='answer_delete'),
    # 답변 수정
    path('answer/modify/<int:id>',views.answer_modify, name='answer_modify'),

    # 질문 등록
    path('question/create/', views.question_create, name='question_create'),

    # 대량의 데이터 등록 - 테스트용
    path('test/makehavy/', views.make_havy_data,)
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
]

board/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    subject = models.CharField(max_length=30)
    content = models.TextField()
    created_at = models.DateTimeField(auto_created = True)
    modified_at = models.DateTimeField(auto_now = True)
    def __str__(self):
        return self.subject

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_created = True)
    modified_at = models.DateTimeField(auto_now = True)
    def __str__(self):
        return self.content

board/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.shortcuts import redirect
from django.utils import timezone
from .models import Question, Answer
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
# Create your views here.


# def index(request):
#     return HttpResponse("나의 첫번째 장고")
def index(request):
    page = request.GET.get('page', '5')
    lists = Question.objects.order_by('-created_at')
    paginator = Paginator(lists,10)
    page_obj = paginator.get_page(page)

    # context = { 'lists' : lists}
    context = { 'lists' : page_obj}
    return render(request, 'board/question_lists.html', context )




def detail(request,id):
    # detail = Question.objects.get(id=id)
    question = get_object_or_404(Question,pk=id)
    context = { 'question' : question}
    return render(request, 'board/question_detail.html', context )

def answer_create(request,id):
    question = get_object_or_404(Question,pk=id)
    answer = Answer(question = question,content = request.POST.get('content'),created_at=timezone.now())
    answer.save()
    # return HttpResponse('등록성공')
    return redirect("detail",id=id)
def answer_delete(request, id):
    answer = get_object_or_404(Answer,pk=id)
    answer.delete()
    return redirect('detail', id=answer.question.id)

@csrf_exempt
def answer_modify(request, id):
    try:
        content =  request.POST.get('content')
        answer = get_object_or_404(Answer,pk=id)
        answer.content = content
        answer.save()
        return JsonResponse({"success":True})
    except:
        return JsonResponse({"success":False, "error":"error"})


def question_create(request):
    question = Question(subject = request.POST.get('subject'), content = request.POST.get('content'),created_at=timezone.now())
    question.save()
    return redirect("/board")




# 대량의 데이터 생성하기 - 테스트용
def make_havy_data(request):
    for i in range(100):
        question = Question(subject = f'제목 {i}', content = f'내용 {i}',created_at=timezone.now())
        question.save()
    return   HttpResponse("대량데이터 등록 성공")

templates/board/question_detail copy.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css'  %}">
</head>
<body>
    {% if detail.created_at %}
        <h1>{{detail.subject}}</h1>
        <h4>{{detail.content}}</h1>
    {% endif %}
    <h5>{{detail.answer_set.count}} 개의 답변이 있습니다</h5>
    <ul>
        {% for a in detail.answer_set.all %}
            <li>{{a.content}}</li>
        {% endfor %}
    </ul>

    <form action="{% url 'answer_create' detail.id  %}" method="post">
        {% csrf_token %}
        <textarea name="content" id="content" rows="15"></textarea>
        <input type="submit" value="답변등록">
    </form>
</body>
</html>

templates/board/question_detail.html
{% extends 'base.html' %}
{% block content %}
    <script>
        $(document).ready(function(){
            $(".btn-danger").click(function(e){
                e.preventDefault();
                if(confirm('정말로 삭제 하겠습니까?')){
                    location.href = e.delegateTarget.dataset.uri;
                }
            })   
            // 수정버튼
            let modify_uri = ''
            $(".btn-warning").click(function(e){
                e.preventDefault();
                const content = $(this).siblings(".card-text").text();
                $("#editinput").val(content);
                modify_uri = e.currentTarget.dataset.uri
                $("#editModal").modal("show");
                // location.href = e.delegateTarget.dataset.uri;               
            })   
            // 모달 수정 버튼  수정내용으로 url 호출해서 수정로직을 수행
            $('#answer_modify').click(function(){
                let modify_content = $('#editinput').val();
                // ajax 요청
                $.ajax({
                    url:modify_uri,
                    method: "POST",
                    data:{
                        content:modify_content,
                        csrfmiddlewaretoken: '{{csrf_token}}'
                    },
                    success:function(data){
                        location.reload(); //현재페이지 리 로드
                    },
                    error: function(){
                        alert("수정에 실패 했습니다. ");
                    }
                });
                
            });

        });
    </script>

    <!-- 게시글 제목과 내용 -->
    {% if question.created_at %}
        <h1 class="mb-4">{{ question.subject }}</h1>
        <p class="lead">{{ question.content }}</p>
    {% endif %}
    
    <!-- 답변 개수 -->
    <h5>{{ question.answer_set.count }} 개의 답변이 있습니다</h5>
    
    <!-- 답변 리스트 -->    
        {% for a in question.answer_set.all %}
        <div class="card" style="width: 18rem;">
            <div class="card-body">                            
              <p class="card-text">{{a.content}}</p>
              <a  class="btn btn-warning" data-uri = "{% url 'answer_modify' a.id %}">수정</a>
              <a data-uri = "{% url 'answer_delete' a.id %}" class="btn btn-danger">삭제</a>
            </div>
          </div>
        {% endfor %}
    

    <!-- 답변 폼 -->
    <form action="{% url 'answer_create' question.id %}" method="post" class="mt-4">
        {% csrf_token %}
        <div class="mb-3">
            <textarea name="content" id="content" rows="5" class="form-control" placeholder="답변을 작성해주세요..."></textarea>
        </div>
        <button type="submit" class="btn btn-primary">답변등록</button>
    </form>


<!-- Button trigger modal -->
<!-- <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
    Launch demo modal
  </button> -->
  
  <!-- Modal -->
  <div class="modal fade" id="editModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">댓글 수정</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <input type="text" id="editinput">
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">취소</button>
          <button type="button" class="btn btn-primary" id = 'answer_modify'>수정</button>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

    

templates/board/question_lists copy.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">제목</th>
            <th scope="col">시간</th>            
        </tr>
        </thead>
        {% if lists %}
            <tbody>
                {% for q in lists %}                                
                    <tr>
                        <th scope="row">1</th>
                        <td><a href="{% url 'detail' q.id  %}" >{{q.subject}}</a></td>
                        <td>{{q.created_at}}</td>            
                    </tr>
                {% endfor %}             
            </tbody>
        {% else %}
            <p>내용이 없습니다.</p>
        {% endif %}
    </table>
    <form action="{% url 'question_create' %}" , method="POST">
        {% csrf_token %}
        <input type="text" name = 'subject' placeholder="제목을 작성해주세요..."><br>
        <textarea name="content" id="content" rows="5" class="form-control" placeholder="내용을 작성해주세요..."></textarea>
        <input type="submit" class="btn btn-primary" value="등록하기">
    </form>
    

</div>
{% endblock %}

templates/board/question_lists.html
{% extends 'base.html' %}
{% block content %}
    <table class="table">
        <thead>
        <tr>            
            <th scope="col">제목</th>
            <th scope="col">시간</th>            
        </tr>
        </thead>
        {% if lists %}
            <tbody>
                {% for q in lists %}                                
                    <tr>                        
                        <td><a href="{% url 'detail' q.id  %}" >{{q.subject}}</a></td>
                        <td>{{q.created_at}}</td>            
                    </tr>
                {% endfor %}             
            </tbody>
        {% else %}
            <p>내용이 없습니다.</p>
        {% endif %}
    </table>
    <form action="{% url 'question_create' %}" , method="POST">
        {% csrf_token %}
        <input type="text" name = 'subject' placeholder="제목을 작성해주세요..."><br>
        <textarea name="content" id="content" rows="5" class="form-control" placeholder="내용을 작성해주세요..."></textarea>
        <input type="submit" class="btn btn-primary" value="등록하기">
    </form> 

    <nav aria-label="Page navigation">
        <ul class="pagination">
          <!-- 이전 버튼 -->
          {% if lists.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?page={{ lists.previous_page_number }}" aria-label="Previous">Previous</a>
            </li>
          {% else %}
            <li class="page-item disabled">
              <a class="page-link" href="#" aria-label="Previous">Previous</a>
            </li>
          {% endif %}
      
          <!-- 페이지 번호 -->
          {% for page_number in lists.paginator.page_range %}
            {% if page_number >= lists.number|add:-5 and page_number <= lists.number|add:5 %}
              <li class="page-item {% if page_number == lists.number %}active{% endif %}">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
              </li>
            {% endif %}
          {% endfor %}
      
          <!-- 다음 버튼 -->
          {% if lists.has_next %}
            <li class="page-item">
              <a class="page-link" href="?page={{ lists.next_page_number }}" aria-label="Next">Next</a>
            </li>
          {% else %}
            <li class="page-item disabled">
              <a class="page-link" href="#" aria-label="Next">Next</a>
            </li>
          {% endif %}
        </ul>
      </nav>
{% endblock %}